apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pawanpoudel-com-tls
spec:
  secretName: pawanpoudel-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pawanpoudel.com
  dnsNames:
    - pawanpoudel.com
    - www.pawanpoudel.com
